### ISSUE TITLE
新问题来了！页脚顺序好像怎么改都是在下面的 我想在上方显示

### ISSUE THREAD

**Issue by yeminxi** [yuang01/hexo-theme-bamboo#43]
![](https://ymxpic.pages.dev/file/2d5397ac15ebd322369a5.png)

**Comment by yeminxi** [comment]
https://ymxpic.pages.dev/file/2d5397ac15ebd322369a5.png

**Comment by yeminxi** [comment]
无法加载 https://utteranc.es/page-attributes.ts 的内容（HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE）

**Comment by yeminxi** [comment]
不好意思打扰了 原因是我本来_config.yml里面也有一个图片懒加载然后主题里也有个冲突了导致出不来，现在已经可以了。

**Comment by yuang01** [comment]
嗯嗯，好的

**Comment by yeminxi** [comment]
> 嗯嗯，好的
如图
![image](https://github.com/yuang01/hexo-theme-bamboo/assets/169566216/d6200a66-0b06-4d28-8b27-5ca849ea1d6f)

**Comment by yuang01** [comment]
这样写，例如我这里增加了一个aa, bb名字随便取
```yaml
# 设置网站页脚
site_footer:
  # 通过layout控制页脚元素的显示和顺序
  # busuanzi是访客数那个,假如说你想在 social和 copyright中间加一个自定义内容, 可以这样写 layout: [social, aaa ,copyright, busuanzi, custom], 然后在下面写上aaa: 'markdown格式', aaa这个名称随便取
  layout: [aa, bb, social, copyright, custom]
  aa: '[Hello World](http://baidu.com)'
  bb: '你好呀，你好呀'
  social:
    - icon: fas fa-rss
      url: /atom.xml
    - icon: fas fa-envelope
      url: mailto:xxxxxxxxx@qq.com
    - icon: fab fa-github
      url: https://github.com/yuang01/hexo-theme-bamboo
    - icon: fab fa-qq
      url: tencent://AddContact/?fromId=50&fromSubId=1&subcmd=all&uin=xxxxxxxxx
  copyright: 'Copyright © 2019 - 2023 <a href="https://github.com/yuang01">yuang01</a> | Powered by <a href="https://hexo.io/zh-cn/docs/">Hexo</a> | Theme <a href="https://github.com/yuang01/theme">Bamboo</a> '
  custom: # 根据需要自行取消注释，label: 'markdown格式'，会在下面继续增加内容
    # - label: '<br>'
    # - label: '[Hello World](http://baidu.com)'
```

1. 上面的layout里面，加上aa, bb,  例如layout: [aa, bb, social, copyright, custom]
2. aa: '我是aa'
3. bb: '我是bb'
4. 如果你想让bb显示在aa的前面，则layout: [bb, aa, social, copyright, custom]
