### ISSUE TITLE
如何设置页面宽度

### ISSUE THREAD

**Issue by Nxhhhh** [yuang01/hexo-theme-bamboo#44]
我想将文章页面的宽度加宽，并且调小字体，望指教。

**Comment by yuang01** [comment]
1. 首先在根目录下的`source`文件夹下创建一个文件夹`custom/index.css`，名字随便取
2. 在`custom/index.css`里写入如下内容，css可自行新增或修改
``` css
.post-detail-content {
    width: 88%; /* 宽度默认75%， */
}
.post-detail-content p { 
    font-size: 14px;
}
/* 其他元素字体大小，自己可以通过增加css来设置，这里只改了p文本元素的字体大小 */
```
3. 找到主题下的`themes\hexo-theme-bamboo\_config.yml`配置文件，找到`import`这个配置，将自定义的css导入进去，写法如下
``` ymal
# 自己嵌入css或者script
import:
  link:
    - <link href="/custom/index.css" rel="stylesheet">
```
就行了的
